---
abstract: 'run perl code in a new process without quoting it, on any OS'
author:
  - 'Christian Walde <walde.christian@googlemail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  strict: 0
  utf8: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ExtUtils-Scriptlet
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  ExtUtils::Scriptlet:
    file: lib/ExtUtils/Scriptlet.pm
    version: 1.132060
requires:
  Data::Dumper: 0
  Exporter: 0
  autodie: 0
  perl: 5.008
  strictures: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=ExtUtils-Scriptlet
  homepage: https://github.com/wchristian/ExtUtils-Scriptlet
  repository: https://github.com/wchristian/ExtUtils-Scriptlet.git
version: 1.132060
